#!/bin/bash
echo 'unsatisfiable' >  solution.txt
num_colors=0
num_nodes=$1
probability=$2

#./generator.py $num_nodes $probability > graph.txt
cat graph.txt
while grep 'unsatisfiable' solution.txt; do
   num_colors=$(($num_colors+1))
   ./main.py $num_colors < graph.txt > solution.txt
   grep -v 'unsatisfiable' solution.txt
done;

